server:
  port: 9094

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: RentCar_UserProfile
      username: rentCarUser
      password: rentACarUser*

jwt:
  secretKey: ${java13secretkey}
  audience: ${java13audience}
  issuer:   ${java13issuer}

rabbitmq:
  exchange: auth-exchange
  queue: auth-queue
  binding_key: auth-binding-key