server:
  port: 9094

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: RentCar_UserProfile
      username: rentCarUser
      password: rentACarUser*

jwt:
  secretKey: ${java13secretkey}
  audience: ${java13audience}
  issuer:   ${java13issuer}