server:
  port: 8090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: RentCar_Vehicle
      username: rentCarVehicleAdmin
      password: rentCarVehicleAdmin*
  elasticsearch:
    uris: http://localhost:9200
    username: admin
    password: root