server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RentCar_AuthDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${java13secretkey}
  audience: ${java13audience}
  issuer:   ${java13issuer}