package com.elif.utility.enums;

public enum EModel {

    MERCEDES_CLS,
    MERCEDES_GLE,
    BMW_3_SERIES,
    BMW_X5,
    FIAT_500,
    FIAT_PANDA,
    FORD_FOCUS,
    FORD_FIESTA,
    TOYOTA_CAMRY,
    TOYOTA_COROLLA,
    OPEL_ASTRA,
    OPEL_CORSAC,
    VOLKSWAGEN_GOLF,
    VOLKSWAGEN_PASSAT,
    AUDI_A4,
    AUDI_Q5,
    SKODA_OCTAVIA,
    SKODA_SUPERB,
    PORSCHE_911,
    PORSCHE_CAYENNE,
    JAGUAR_XE,
    JAGUAR_FPACE,
    HONDA_ACCORD,
    HONDA_CIVIC
}
