package com.elif.utility.enums;

public enum ELocation {
    ISTANBUL_USKUDAR,
    ISTANBUL_KADIKOY,
    ISTANBUL_SARIYER,
    ISTANBUL_BESIKTAS,
    ANKARA_CANKAYA,
    ANKARA_MALTEPE,
    ANKARA_YENIMAHALLE
}
